In [1]:
import pandas as pd

In [3]:
LoanData = pd.read_csv("01Exercise1.csv")

In [4]:
Loanprep = LoanData.copy()

In [5]:
Loanprep.size

3684

In [6]:
# identify missing value
Loanprep.isnull().sum(axis=0)

gender     13
married     3
ch         50
income      0
loanamt    22
status      0
dtype: int64

In [8]:
Loanprep = Loanprep.dropna()

In [9]:
Loanprep

     gender married   ch  income  loanamt status
1      Male     Yes  1.0    4583    128.0      N
2      Male     Yes  1.0    3000     66.0      Y
3      Male     Yes  1.0    2583    120.0      Y
4      Male      No  1.0    6000    141.0      Y
5      Male     Yes  1.0    5417    267.0      Y
..      ...     ...  ...     ...      ...    ...
609  Female      No  1.0    2900     71.0      Y
610    Male     Yes  1.0    4106     40.0      Y
611    Male     Yes  1.0    8072    253.0      Y
612    Male     Yes  1.0    7583    187.0      Y
613  Female      No  0.0    4583    133.0      N

[529 rows x 6 columns]

In [13]:
#drop the irrelevent column of the gender
Loanprep = Loanprep.drop(['gender'], axis = 1)

In [14]:
Loanprep.dtypes

married     object
ch         float64
income       int64
loanamt    float64
status      object
dtype: object

In [15]:
#get dummies

Loanprep = pd.get_dummies(Loanprep, drop_first=True)

In [16]:
Loanprep

      ch  income  loanamt  married_Yes  status_Y
1    1.0    4583    128.0         True     False
2    1.0    3000     66.0         True      True
3    1.0    2583    120.0         True      True
4    1.0    6000    141.0        False      True
5    1.0    5417    267.0         True      True
..   ...     ...      ...          ...       ...
609  1.0    2900     71.0        False      True
610  1.0    4106     40.0         True      True
611  1.0    8072    253.0         True      True
612  1.0    7583    187.0         True      True
613  0.0    4583    133.0        False     False

[529 rows x 5 columns]

In [17]:
#Normalize the data for loanamt and income

from sklearn.preprocessing import StandardScaler
scaler_ = StandardScaler()

In [19]:
Loanprep['income'] = scaler_.fit_transform(Loanprep[['income']])
Loanprep['loanamt'] = scaler_.fit_transform(Loanprep[['loanamt']])

In [20]:
Loanprep

      ch    income   loanamt  married_Yes  status_Y
1    1.0 -0.128073 -0.194250         True     False
2    1.0 -0.392077 -0.971015         True      True
3    1.0 -0.461621 -0.294478         True      True
4    1.0  0.108246 -0.031380        False      True
5    1.0  0.011017  1.547205         True      True
..   ...       ...       ...          ...       ...
609  1.0 -0.408754 -0.908372        False      True
610  1.0 -0.207624 -1.296754         True      True
611  1.0  0.453802  1.371807         True      True
612  1.0  0.372249  0.544929         True      True
613  0.0 -0.128073 -0.131608        False     False

[529 rows x 5 columns]

In [23]:
# create x and y variable
Y = Loanprep[['status_Y']]
X = Loanprep.drop(['status_Y'], axis = 1)

In [24]:
# split dataset into traning and testing
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=1234, stratify=Y)

In [25]:
x_test

      ch    income   loanamt  married_Yes
373  0.0 -0.381737 -0.407234        False
464  0.0 -0.197618 -0.570104        False
3    1.0 -0.461621 -0.294478         True
262  1.0 -0.311858  0.144018        False
401  1.0 -0.432936 -0.983543        False
..   ...       ...       ...          ...
360  1.0 -0.104725 -0.783088        False
71   1.0 -0.579698 -0.582632         True
96   1.0 -0.478132 -0.081494         True
388  1.0 -0.503315 -0.094023         True
270  1.0 -0.352551 -1.422039        False

[159 rows x 4 columns]

In [26]:
y_test

     status_Y
373     False
464     False
3        True
262     False
401     False
..        ...
360     False
71       True
96       True
388      True
270      True

[159 rows x 1 columns]

In [27]:
# Build the logistic regrssion model
from sklearn.linear_model import LogisticRegression

In [28]:
lr = LogisticRegression()

In [29]:
lr.fit(x_train, y_train)

C:\Users\Komal\AppData\Roaming\Python\Python311\site-packages\sklearn\utils\validation.py:1229: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [30]:
y_predict = lr.predict(x_test)

In [31]:
y_predict  # compare with y_test it is correct or not

array([False, False,  True,  True,  True, False,  True,  True, False,
        True,  True, False,  True, False, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False,  True,  True,  True, False,
        True,  True, False,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True, False,  True, False,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True,  True,  True, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True])

In [32]:
y_test

     status_Y
373     False
464     False
3        True
262     False
401     False
..        ...
360     False
71       True
96       True
388      True
270      True

[159 rows x 1 columns]

In [33]:
# Build the confussion matrix and get the acurate result
from sklearn.metrics import confusion_matrix

In [35]:
cm = confusion_matrix(y_test, y_predict)

In [36]:
cm

array([[ 29,  20],
       [  2, 108]], dtype=int64)

In [37]:
score = lr.score(x_test, y_test)

In [38]:
score

0.8616352201257862